name: Desplegar en GitHub Pages

# Se ejecuta cada vez que haces un push a la rama 'develop'
on:
  push:
    branches:
      - develop # Asegúrate de que esta es tu rama de desarrollo principal

jobs:
  build-and-deploy:
    # Otorga permisos para que la Action pueda escribir en la rama gh-pages
    permissions:
      contents: write

    # Usamos la última versión de Ubuntu para ejecutar el trabajo
    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en el runner de GitHub Actions
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala wasm-pack, la herramienta para compilar Rust a WASM para la web
      - name: Instalar wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      # 3. Compila tu crate de Rust a WASM
      #    Compila el crate 'rust-crypto' y coloca los archivos de salida
      #    en 'frontend/pkg', que es donde 'main.js' los espera.
      - name: Compilar WASM
        run: wasm-pack build ./rust-crypto --target web --out-dir ./frontend/pkg

      # 4. Despliega los archivos estáticos a la rama 'gh-pages'
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # El token es necesario para permitir que la acción escriba en tu repositorio
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # El directorio que se publicará. Contiene todos los archivos del frontend.
          publish_dir: ./frontend
