name: Desplegar en GitHub Pages

# Se ejecuta cada vez que haces un push a la rama 'main'
on:
  push:
    branches:
      - develop # Ahora se ejecuta en la rama 'develop'

jobs:
  build-and-deploy:
    # Usamos la última versión de Ubuntu para ejecutar el trabajo
    permissions:
      contents: write # Permite a la Action escribir en el repositorio (crear la rama gh-pages)

    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en el runner de GitHub Actions
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala wasm-pack, la herramienta para compilar Rust a WASM para la web
      - name: Instalar wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      # 3. Compila tu crate de Rust a WASM
      #    - Asume que tu crate está en la carpeta 'rust-crypto'
      #    - '--target web' crea un output compatible con ES Modules
      #    - '--out-dir ./frontend/pkg' coloca los archivos compilados dentro de la carpeta 'frontend/pkg',
      #      justo donde tu 'main.js' espera encontrarlos.
      - name: Construir el sitio
        # Añadimos --verbose para obtener más detalles en caso de error
        run: |
          set -ex
          # Compila el WASM y lo coloca directamente dentro de la carpeta del frontend.
          # Ahora la carpeta 'frontend' contiene el sitio web completo y listo para desplegar.
          wasm-pack build --verbose ./rust-crypto --target web --out-dir ./frontend/pkg

      # Verificación y depuración: Listar el contenido del directorio 'frontend'
      # Si este paso falla, significa que la compilación en el paso anterior no generó los archivos esperados.
      - name: Listar y verificar contenido del frontend
        run: |
          echo "--- Verificando contenido de ./frontend/pkg ---"
          ls -l ./frontend/pkg/
          echo "--- Listando todo el contenido de ./frontend ---"
          ls -R ./frontend

      # 4. Despliega los archivos estáticos a la rama 'gh-pages'
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # El token es necesario para permitir que la acción escriba en tu repositorio
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publica directamente el contenido de la carpeta 'frontend'.
          publish_dir: ./frontend
          # Crea una rama 'gh-pages' limpia en cada despliegue para evitar archivos antiguos.
          force_orphan: true