name: Desplegar en GitHub Pages

# Se ejecuta cada vez que haces un push a la rama 'main'
on:
  push:
    branches:
      - develop # Ahora se ejecuta en la rama 'develop'

jobs:
  build-and-deploy:
    # Usamos la última versión de Ubuntu para ejecutar el trabajo
    permissions:
      contents: write # Permite a la Action escribir en el repositorio (crear la rama gh-pages)

    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en el runner de GitHub Actions
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala wasm-pack, la herramienta para compilar Rust a WASM para la web
      - name: Instalar wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      # 3. Compila tu crate de Rust a WASM
      #    - Asume que tu crate está en la carpeta 'rust-crypto'
      #    - '--target web' crea un output compatible con ES Modules
      #    - '--out-dir ./frontend/pkg' coloca los archivos compilados dentro de la carpeta 'frontend/pkg',
      #      justo donde tu 'main.js' espera encontrarlos.
      - name: Construir artefacto de despliegue
        run: |
          # Crea un directorio de distribución limpio
          mkdir ./dist
          # Compila el WASM y lo coloca directamente en la carpeta de distribución
          wasm-pack build ./rust-crypto --target web --out-dir ./dist/pkg
          # Copia los archivos estáticos del frontend a la carpeta de distribución
          cp ./frontend/index.html ./frontend/main.js ./frontend/style.css ./dist/

      # Debug: Listar el contenido del directorio 'dist' antes de publicar
      - name: Listar contenido de dist
        run: |
          ls -R ./dist

      # 4. Despliega los archivos estáticos a la rama 'gh-pages'
      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # El token es necesario para permitir que la acción escriba en tu repositorio
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # El directorio que se publicará. Contiene tu index.html, main.js, y la carpeta pkg/ generada.
          publish_dir: ./dist